import os
import time
import clients
#import Player
from config import statusPageLocation
import cPickle as Pickle

'''
Created on Dec 3, 2009

@author: ghoti
'''
class status:
    def __init__(self):
        self.map = Pickle.load(open(os.path.join('pickles/', 'map'), 'r'))
        self.players = Pickle.load(open(os.path.join('pickles/', 'players'), 'r'))
        self.chat = Pickle.load(open(os.path.join('pickles/', 'chat'), 'r'))
        self.toHTML()
    """
    In the true spirit of GCK and JHF, we are going to print all of the player information to a (not so)
    pretty HTML page that can be made visible to visitors - including chat so that I can taunt people
    who aren't playing but are watching the status page (ahh memories)

    TODO: include map images!
    """
    def toHTML(self):
        if os.path.isfile(statusPageLocation + "status.html"):
            os.remove(statusPageLocation + "status.html")
        h = open((statusPageLocation + "status.html"), "w")
        #this is quite ugly, i need a webdev guy here
        h.write("<HTML>\n<HEAD>\n\t<meta http-equiv=refresh content=15>\n\t" + \
                    '<style type="text/css">\n\tbody {color: white; background: black;}\n \
                    div {text-align: center; font-size: 1000%;}\n\t</style>\n\t'
                    "<TITLE>Status</TITLE>\n<HEAD>\n<BODY>")
        h.write("<CENTER>=JHF= Games Server Status -- eXtreme -- jhfgames.com<BR>\n" + \
                    "Map: %s -- Players: %i / 20 \n<hr>" % (self.map, len(self.players)))
        h.write("<TABLE ALIGN=CENTER BORDER=3><TR><TD><B>#</B></TD><TD><B>PB</B></TD>" + \
                    "</TD><TD><B>Player</B></TD><TD><B>Kills</B></TD><TD><B>Deaths</B></TD><TD><B>Streak</B></TD><TD><b>Teamkills</b></TD></TR>\n")
        for player in self.players.values():
            h.write("<TR><TD>%s</TD><TD>%s</TD><TD>%s</TD><TD>%s</TD><TD>%s</TD><TD>%s</TD><TD>%s</TD></TR>\n" % \
                   (player.slot, player.pbslot, player.name, player.kills, player.deaths, player.streak, player.teamkills))
        h.write("</TABLE><HR><TABLE ALIGN=CENTER><TR><TD><B>Latest Messages:</B></TD></TR>\n")
        for i in reversed(self.chat):
            h.write("<TR><TD>%s: %s</TR></TD>\n" % (i[0], i[1].strip("^U")))
        h.write("</TABLE><BR><HR>Data generated by Monitor V3 on %s\n" % (time.strftime("%m/%d/%Y %H:%M:%S", time.localtime())))
        h.write("</BODY></HTML>")
        h.close()

if __name__ == "__main__":
    makeitso = status()
